flyway.user=admin
flyway.password=password
flyway.driver=org.h2.Driver
flyway.url=jdbc:h2:file:./target/db;MODE=PostgreSQL
flyway.locations=classpath:db/migration/
flyway.schemas=PRODUCTS_STORE
flyway.cleanDisabled=false