spring:
  jackson:
# https://www.baeldung.com/spring-boot-customize-jackson-objectmapper
# https://codingnconcepts.com/spring-boot/customize-jackson-json-mapper/
# spring.jackson.<category_name>.<feature_name>=true,false
#    default-property-inclusion: non_null
#    default-property-inclusion: non_empty
#    serialization:
#      write-dates-as-timestamps: true
# https://docs.spring.io/spring-boot/docs/2.1.13.RELEASE/reference/html/boot-features-json.html
#  mvc:
#    converters:
#      preferred-json-mapper: gson
#      preferred-json-mapper: jackson
