spring:
  kafka:
    consumer:
      bootstrap-servers:
      - localhost:9091
      - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: group-1
      properties:
        spring:
          json:
            trusted:
              packages: 'ru.otus.java.pro.mt.client.kafkaconsumer.dtos'
    topics:
      transfer-topic: mt.transfers.status.info
logging:
  level:
    ru.otus: DEBUG