server:
  port: 8080
spring:
  application:
    name: mt-core-transfers
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mt_core_transfers
    username: mt_core_transfers_admin
    password: mt_core_transfers_admin
  jpa:
    show-sql: true
    open-in-view: false
transfers:
  max-transfer-sum: 100.00
  demo-transfers-enabled: false
  send-statistics: false
  blocked-account-numbers:
    - "123"
    - "234"
    - "456"
integrations:
  statistics:
    url: http://localhost:8083/api/v1/statistics
    read-timeout: 10s
    connect-timeout: 5s
  limits:
    url: http://localhost:8082/api/v1/limits
    read-timeout: 30s
    connect-timeout: 2s
  base:
    url: http://localhost:8182/api/v1
    read-timeout: 5s
    connect-timeout: 1s
springdoc:
  swagger-ui:
    path: /swagger
logging:
  level:
    org.zalando.logbook.Logbook: TRACE